### ISSUE TITLE
Query file not found || Connector not installed

### ISSUE THREAD

**Issue by abgonzalez93** [latitude-dev/latitude#348]
### Environment

- Node version (`node -v`): 18.20.2
- npm version (`npm -v`): 10.5.2
- Latitude CLI version (`latitude --version`): 1.3.1
- Latitude project version (check `latitude.json` at the root of your project): 1.1.0
- OS: Ubuntu 22.04.3
- Browser: Firefox 125.0.2
- Database: MySQL

## Actual Behaviour
After updating **CLI** and Latitude project to the newest versions and also, installing **MySQL Connector** with the following command

_**npm install --save @latitude-data/mysql-connector**_

I found new **2 errors** on my project:

- **Query file not found:** Even though it was working before the update. It seems like Latitude is trying to get the **SQL file** from another directory inside _.latitude folder_

![imagen](https://github.com/latitude-dev/latitude/assets/39385878/695ec5c4-e79d-43b2-b146-a98a395c0413)

![imagen](https://github.com/latitude-dev/latitude/assets/39385878/5e58e0ca-1ba0-4347-b62c-5554d5631d61)

- **Connector not installed:**
I installed the connector (**@latitude-data/mysql-connector**)
So I don't get why **CLI** is telling me that the connector is not installed yet

![imagen](https://github.com/latitude-dev/latitude/assets/39385878/b4691c45-5874-434c-8f97-7778cbb12d17)

![imagen](https://github.com/latitude-dev/latitude/assets/39385878/e0c54564-c65b-47ad-99af-988581d4ec09)

**Comment by abgonzalez93** [comment]
![imagen](https://github.com/latitude-dev/latitude/assets/39385878/f553dc3e-1607-44b9-885a-9d5c2da1b5f3)

**Comment by geclos** [comment]
Root of the project is where the connectors should be installed, so it looks ok.  Some more questions then, are you running `latitude dev` from the terminal in the root of your project?

**Comment by abgonzalez93** [comment]
I'm always running `latitude dev` command in the root of my project

![imagen](https://github.com/latitude-dev/latitude/assets/39385878/a8939aa9-1096-4cad-8b1d-1a36c1b3c0f5)

**Comment by geclos** [comment]
Ok looks good. I've been able to reproduce the query not found issue and will release a fix asap (today). In the meantime if this is critical i'd suggest to downgrade to a previous latitude version with `latitude update`.

**Comment by abgonzalez93** [comment]
There is also an error in the previous version (1.0.1). It seems it's because of the MySQL connector:

> /home/antoniobueno/Analitica/fieldeas-demo/node_modules/mysql/lib/protocol/Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^

> TypeError: Cannot read properties of undefined (reading 'map')
>     at MysqlConnector.buildQueryParams (file:///home/antoniobueno/Analitica/fieldeas-demo/node_modules/@latitude-data/mysql-connector/dist/index.js:91:23)
>     at file:///home/antoniobueno/Analitica/fieldeas-demo/node_modules/@latitude-data/mysql-connector/dist/index.js:34:50
>     at Handshake.onConnect (/home/antoniobueno/Analitica/fieldeas-demo/node_modules/mysql/lib/Pool.js:64:7)
>     at Handshake.<anonymous> (/home/antoniobueno/Analitica/fieldeas-demo/node_modules/mysql/lib/Connection.js:526:10)
>     at Handshake._callback (/home/antoniobueno/Analitica/fieldeas-demo/node_modules/mysql/lib/Connection.js:488:16)
>     at Sequence.end (/home/antoniobueno/Analitica/fieldeas-demo/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
>     at Sequence.OkPacket (/home/antoniobueno/Analitica/fieldeas-demo/node_modules/mysql/lib/protocol/sequences/Sequence.js:92:8)
>     at Protocol._parsePacket (/home/antoniobueno/Analitica/fieldeas-demo/node_modules/mysql/lib/protocol/Protocol.js:291:23)
>     at Parser._parsePacket (/home/antoniobueno/Analitica/fieldeas-demo/node_modules/mysql/lib/protocol/Parser.js:433:10)
>     at Parser.write (/home/antoniobueno/Analitica/fieldeas-demo/node_modules/mysql/lib/protocol/Parser.js:43:10)
> 
> Node.js v18.20.2

**Comment by abgonzalez93** [comment]
Everything working fine now.
We keep in touch!
